# Generated by Django 2.0.2 on 2020-05-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_auto_20200512_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userleavingmessage',
            name='file',
            field=models.FileField(blank=True, help_text='上传的文件', upload_to='message/images/', verbose_name='上传的文件'),
        ),
    ]
